from __future__ import annotations
import json

def run_to_python(run:dict,flavor:str='pytorch')->str:
    p=run['payload']; probes=p.get('probes',[]); interventions=p.get('interventions',[]); model=p.get('model','resnet18')
    if flavor!='pytorch':
        return '# ModelForge generated reference\n# Requested flavor: '+flavor+'\n# This build emits exact plain-PyTorch code as the canonical form.\n\n'+run_to_python(run,'pytorch')
    lines=[
        f'# Generated by ModelForge from run {run["id"]}',
        'import torch',
        'from torchvision import models',
        '',
        f'MODEL_NAME = {model!r}',
        'PROBES = '+repr(probes),
        'INTERVENTIONS = '+repr(interventions),
        f'SEED = {int(p.get("seed",0))}',
        '',
        'def apply_intervention(out, spec):',
        '    if not isinstance(out, torch.Tensor): return out',
        '    kind=spec["kind"]',
        '    if kind=="ablate": return torch.zeros_like(out)',
        '    if kind=="scale": return out * float(spec.get("value",1.0))',
        '    if kind=="noise": return out + torch.randn_like(out)*float(spec.get("value",0.01))',
        '    if kind=="clamp": return torch.clamp(out, spec.get("min_value",-float("inf")), spec.get("max_value",float("inf")))',
        '    if kind=="detach": return out.detach()',
        '    if kind=="mask" and spec.get("indices") and out.ndim>=2:',
        '        y=out.clone(); idx=torch.tensor(spec["indices"],device=out.device); idx=idx[idx<out.shape[1]]; y.index_fill_(1,idx,0); return y',
        '    return out',
        '',
        'def main():',
        '    torch.manual_seed(SEED)',
        '    model=getattr(models,MODEL_NAME)(weights=None).eval()',
        '    modules=dict(model.named_modules())',
        '    captures={}; handles=[]; ints={}',
        '    for spec in INTERVENTIONS: ints.setdefault(spec["path"],[]).append(spec)',
        '    probe_paths={x["path"] for x in PROBES}',
        '    for path in set(ints)|probe_paths:',
        '        if path not in modules: continue',
        '        def hook(mod,inp,out,path=path):',
        '            actual=out',
        '            for spec in ints.get(path,[]): actual=apply_intervention(actual,spec)',
        '            if path in probe_paths and isinstance(actual,torch.Tensor):',
        '                captures[path]={"shape":list(actual.shape),"rms":float(torch.sqrt((actual.detach().float()**2).mean()))}',
        '            return actual',
        '        handles.append(modules[path].register_forward_hook(hook))',
        f'    x=torch.zeros(1,3,{int(p.get("image_size",96))},{int(p.get("image_size",96))})',
        '    with torch.inference_mode(): y=model(x)',
        '    for h in handles: h.remove()',
        '    print("output",tuple(y.shape)); print("captures",captures)',
        '',
        'if __name__=="__main__": main()',
        ''
    ]
    return '\n'.join(lines)
